### PR TITLE
build(deps): update java-shared-config to v1.7.3

### PR DESCRIPTION
**Pull request by mpeddada1**
Investigation of renovate-bot being unable to update this dependency at #2511

### CODE REVIEW

**Review by zhumin8 — APPROVED** [review]

**Comment by mpeddada1** [comment]
Running into:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:testCompile (default-testCompile) on project google-cloud-spanner-jdbc: Compilation failure: Compilation failure: 
Error:  /home/runner/work/sdk-platform-java/sdk-platform-java/java-shared-dependencies/target/java-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementReturnGeneratedKeysMockServerTest.java:[318,29] cannot find symbol
Error:    symbol:   method pack(com.google.protobuf.Empty)
Error:    location: class com.google.protobuf.Any
Error:  /home/runner/work/sdk-platform-java/sdk-platform-java/java-shared-dependencies/target/java-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/StatementReturnGeneratedKeysMockServerTest.java:[319,29] cannot find symbol
Error:    symbol:   method pack(com.google.spanner.admin.database.v1.UpdateDatabaseDdlMetadata)
Error:    location: class com.google.protobuf.Any
Error:  /home/runner/work/sdk-platform-java/sdk-platform-java/java-shared-dependencies/target/java-spanner-jdbc/src/test/java/com/google/cloud/spanner/jdbc/PreparedStatementReturnGeneratedKeysMockServerTest.java:[318,29] cannot find symbol
```

**Comment by mpeddada1** [comment]
Running the checks from `main` however results in a successful build: https://github.com/googleapis/sdk-platform-java/pull/2513

**Comment by burkedavison** [comment]
Both GraalVM test shows (many) KMS failures that look the same as in java-spanner.
https://source.cloud.google.com/results/invocations/8de16815-7841-4778-b7b2-5d4a73b02211

Example failure:
```
Warning: Could not register com.google.cloud.location.Location$Builder: queryAllPublicConstructors for reflection. Reason: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/google/cloud/location/Location$Builder.setMetadata(Lcom/google/protobuf/Any$Builder;)Lcom/google/cloud/location/Location$Builder; @26: invokevirtual
  Reason:
    Type 'com/google/protobuf/Any' (current frame, stack[1]) is not assignable to 'com/google/protobuf/AbstractMessage'
  Current Frame:
    bci: @26
    flags: { }
    locals: { 'com/google/cloud/location/Location$Builder', 'com/google/protobuf/Any$Builder' }
    stack: { 'com/google/protobuf/SingleFieldBuilderV3', 'com/google/protobuf/Any' }
  Bytecode:
    0000000: 2ab4 001f c700 0e2a 2bb6 0076 b500 1ea7
    0000010: 000f 2ab4 001f 2bb6 0076 b600 7557 2a59
    0000020: b400 1c10 1080 b500 1c2a b600 3d2a b0  
  Stackmap Table:
    same_frame(@18)
    same_frame(@30)
```

**Comment by zhumin8** [comment]
Hit same error with java-shared-config v 1.7.2 (without graal-sdk to v22.3.5 upgrade): [workflow logs](https://github.com/googleapis/sdk-platform-java/actions/runs/8082666717/job/22084004509?pr=2516)

**Pull request closed without merging**
