### PR TITLE
fix: cleanup @BetaApi from Resource Name Builder Methods 

### LINKED ISSUE #2099: generator: Remove @BetaApi from Resource Name Builder Methods
1. Per-pattern Builders
    * Example: https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/BlurbName.java#L372
    * Example: https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/BlurbName.java#L403
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposer.java#L510

2. Static factory methods
    * Example: https://github.com/googleapis/sdk-platform-java/blob/decd7f60017d45288e6c12493fa21e06f9c5f77c/showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/BlurbName.java#L149-L171
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blob/main/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposer.java#L604-L606

3. Static format methods
    * Example: https://github.com/googleapis/sdk-platform-java/blob/decd7f60017d45288e6c12493fa21e06f9c5f77c/showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/BlurbName.java#L177C13-L200
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blob/main/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposer.java#L604-L606

### PR DESCRIPTION
**Pull request by zhumin8**
fixes #2099

### CODE REVIEW

**Comment by lqiu96** [comment]
Should this one be removed as well? https://github.com/googleapis/sdk-platform-java/blob/3b36de7e5c699e056950d980e7ce4c280c9490dc/gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/resourcename/goldens/AgentName.golden#L224 from https://github.com/googleapis/sdk-platform-java/blob/ed21464d75eaa97743a63285be64fcca6e8f4cf2/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposer.java#L1703-L1711

**Comment by zhumin8** [comment]
> Should this one be removed as well?
> 
> https://github.com/googleapis/sdk-platform-java/blob/3b36de7e5c699e056950d980e7ce4c280c9490dc/gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/resourcename/goldens/AgentName.golden#L224

Yes. Thanks for catching this.

**Comment by zhumin8** [comment]
I am a bit confused. I followed [this guide](https://github.com/googleapis/sdk-platform-java/blob/main/showcase/README.md#update-the-golden-showcase-files) to update golden files for showcase, and showcase ci tests are passing. 
But I noticed there are still appearances of "per-pattern builders" under showcase folder: 
https://github.com/googleapis/sdk-platform-java/blob/14dd389fc9cb3cae1c3868456a1171ae65de8dca/showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/BlurbName.java#L121-L136

@lqiu96 I am missing anything in my workflow? Or is this class not part of showcase golden?

**Comment by lqiu96** [comment]
> I am a bit confused. I followed [this guide](https://github.com/googleapis/sdk-platform-java/blob/main/showcase/README.md#update-the-golden-showcase-files) to update golden files for showcase, and showcase ci tests are passing. But I noticed there are still appearances of "per-pattern builders" under showcase folder:
> 
> https://github.com/googleapis/sdk-platform-java/blob/14dd389fc9cb3cae1c3868456a1171ae65de8dca/showcase/gapic-showcase/proto/src/main/java/com/google/showcase/v1beta1/BlurbName.java#L121-L136
> 
> @lqiu96 I am missing anything in my workflow? Or is this class not part of showcase golden?

I suspect that you are made gapic-generator changes and need to re-run `mvn clean install`. I think showcase is pointed to use the SNAPSHOT version and the version it's using is the pre-generator changes. Can you try re-installing and let me know if that updates correctly.

**Comment by lqiu96** [comment]
Ah one more thing, can you double check if the `FIXED_TYPESTORE` has `BetaApi.class` reference in there? If all the betaapi references are removed from this composer, can you remove it from there as well?

**Review by lqiu96 — APPROVED** [review]

**Pull request merged**
