### PR TITLE
fix: remove duplicated calls to AutoValue builders

### LINKED ISSUE #2635: Duplicate calls to setters in gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest
There are some duplicated calls to setter methods in `gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java`:

https://github.com/googleapis/sdk-platform-java/blob/3fbcdebdb8ff4444294a82578b7326788b125ef0/gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java#L201-L202

The calls are redundant, can can be removed.

These were noticed by https://errorprone.info/bugpattern/RedundantSetterCall

### PR DESCRIPTION
**Pull request by cushon**
This change removes duplicate calls to setters in `gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java`.

Fixes #2635 ☕️

### CODE REVIEW

**Comment by blakeli0** [comment]
@cushon Thanks for raising this PR! Please change the PR title by following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by cushon** [comment]
> @cushon Thanks for raising this PR! Please change the PR title by following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

Done, thanks for taking a look!

**Review by lqiu96 — APPROVED** [review]

**Pull request merged**
