### PR TITLE
chore: migrate library generation IT to cloud build

### PR DESCRIPTION
**Pull request by JoeWang1127**
In this PR:
- Add an integration test running in Cloud Build to verify the library generation image.

### CODE REVIEW

**Comment by blakeli0** [comment]
Based on what @chingor13  shared last Wednesday, I think the infra team is leaning towards using kokoro for integration tests, there might still be a case for using Cloud Build if it is much easier to migrate, but I think we should at least evaluate kokoro. cc: @meltsufin

**Review by suztomo — APPROVED** [review]

**Comment by JoeWang1127** [comment]
> Based on what @chingor13 shared last Wednesday, I think the infra team is leaning towards using kokoro for integration tests, there might still be a case for using Cloud Build if it is much easier to migrate, but I think we should at least evaluate kokoro. cc: @meltsufin

@blakeli0 Thanks for this info.

I'm trying to migrate the IT to cloud build first but Kokoro is an alternative if cloud build doesn't work out.

**Comment by JoeWang1127** [comment]
Volume binding `-v /tmp/tmpncy0ek3m:/workspace/api` seems wrong:
```

build_file_folder: /workspace/repo/output/google/cloud/apigeeconnect/v1
--
14:11:51 | Traceback (most recent call last):
14:11:51 | File "/src/library_generation/cli/entry_point.py", line 180, in <module>
14:11:51 | main()
14:11:51 | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
14:11:51 | return self.main(*args, **kwargs)
14:11:51 | ^^^^^^^^^^^^^^^^^^^^^^^^^^
14:11:51 | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
14:11:51 | rv = self.invoke(ctx)
14:11:51 | ^^^^^^^^^^^^^^^^
14:11:51 | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
14:11:51 | return _process_result(sub_ctx.command.invoke(sub_ctx))
14:11:51 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:11:51 | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
14:11:51 | return ctx.invoke(self.callback, **ctx.params)
14:11:51 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:11:51 | File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
14:11:51 | return __callback(*args, **kwargs)
14:11:51 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:11:51 | File "/src/library_generation/cli/entry_point.py", line 94, in generate
14:11:51 | __generate_repo_impl(
14:11:51 | File "/src/library_generation/cli/entry_point.py", line 128, in __generate_repo_impl
14:11:51 | generate_from_yaml(
14:11:51 | File "/usr/local/lib/python3.12/site-packages/library_generation/generate_repo.py", line 59, in generate_from_yaml
14:11:51 | generate_composed_library(
14:11:51 | File "/usr/local/lib/python3.12/site-packages/library_generation/generate_composed_library.py", line 67, in generate_composed_library
14:11:51 | gapic_inputs = parse_build_file(build_file_folder, gapic.proto_path)
14:11:51 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:11:51 | File "/usr/local/lib/python3.12/site-packages/common/model/gapic_inputs.py", line 101, in parse
14:11:51 | with open(f"{build_path}/{build_file_name}") as build:
14:11:51 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:11:51 | FileNotFoundError: [Errno 2] No such file or directory: '/workspace/repo/output/google/cloud/apigeeconnect/v1/BUILD.bazel'
14:11:51 | E
14:11:51 | ======================================================================
14:11:51 | ERROR: test_entry_point_running_in_container (hermetic_build.library_generation.tests.integration_tests_cloud_build.IntegrationTest.test_entry_point_running_in_container)
14:11:51 | ----------------------------------------------------------------------
14:11:51 | Traceback (most recent call last):
14:11:51 | File "/workspace/hermetic_build/library_generation/tests/integration_tests_cloud_build.py", line 92, in test_entry_point_running_in_container
14:11:51 | self.__run_entry_point_in_docker_container(
14:11:51 | File "/workspace/hermetic_build/library_generation/tests/integration_tests_cloud_build.py", line 303, in __run_entry_point_in_docker_container
14:11:51 | subprocess.check_call(
14:11:51 | File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
14:11:51 | raise CalledProcessError(retcode, cmd)
14:11:51 | subprocess.CalledProcessError: Command '['docker', 'run', '-u', '0:0', '--rm', '--quiet', '--network', 'none', '-v', '/workspace/output/google-cloud-java:/workspace/repo', '-v', '/workspace/hermetic_build/library_generation/tests/resources/integration/golden/../google-cloud-java:/workspace/config', '-v', '/tmp/tmpncy0ek3m:/workspace/api', '-v', '/workspace/hermetic_build/library_generation/tests/resources/integration/gapic-generator-java.jar:/home/.library_generation/gapic-generator-java.jar', '-w', '/workspace/repo', 'test-image:latest', '--generation-config-path=/workspace/config/generation_config.yaml', '--api-definitions-path=/workspace/api']' returned non-zero exit status 1.
```

**Comment by JoeWang1127** [comment]
I'll investigate how to copy API definitions from cloud storage to cloud build.

**Pull request merged**
