### PR TITLE
chore: use java-graalvm-ci-prod gcp project for running tests

### PR DESCRIPTION
**Pull request by mpeddada1**
This PR migrates the presubmits in sdk-platform-java to `java-graalvm-ci-prod`.

### CODE REVIEW

**Comment by mpeddada1** [comment]
Stacktrace:

```
[0m [0m[1m[31mError: [0m[0m[1mError when reading or editing Project Service : Request `List Project Services java-graalvm-ci-prod` returned error: Batch request and retried single request "List Project Services java-graalvm-ci-prod" both failed. Final error: Failed to list enabled services for project java-graalvm-ci-prod: googleapi: Error 403: Permission denied to list services for consumer container
```

**Comment by mpeddada1** [comment]
Stacktrace after enabling cloudkms.googleapis.com in `java-graalvm-ci-prod`:
```
 ITKmsTest.ensureKmsKeyRingExists:60->getKeyRing:76 » StatusRuntime PERMISSION_DENIED: Permission 'cloudkms.keyRings.get' denied on resource 'projects/java-graalvm-ci-prod/locations/us/keyRings/gcs_test_kms_key_ring' (or it may not exist).
```

**Comment by mpeddada1** [comment]
The presubmits running on `java-graalvm-ci-prod` are now passing.

**Review by jinseopkim0 — COMMENTED** [review]
Retrying the failed library_generation test
```
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 2366 bytes of body are still expected
```
https://github.com/googleapis/sdk-platform-java/actions/runs/11823555090/job/32943111452?pr=3349

**Review by suztomo — APPROVED** [review]
The required GraalVM checks passed

**Comment by burkedavison** [comment]
Please don't merge until all the GraalVM checks are passing.

**Comment by burkedavison** [comment]
Discussed with Mridula. Approved. The failing checks are duplicates and legacy.

**Review by burkedavison — APPROVED** [review]

**Pull request merged**
