### PR TITLE
fix: `BaseApiTracer` to noop on attemptFailed via overloaded method call

### PR DESCRIPTION
**Pull request by diegomarquezp**
Fixes https://github.com/googleapis/sdk-platform-java/issues/3015
Fixes https://github.com/googleapis/sdk-platform-java/issues/3014

Gax tracing internally works with `attemptFailedDuration`, which defaults to a no-op. Downstream libraries use `attemptFailed`, which has a custom behavior. What happens when an attempt-failed event occurs is that `attemptFailedDuration` is called instead (in favor of using java.time methods internally). This fix makes `attemptFailedDuration`'s behavior to delegate the logic to `attemptFailed`.

The downstreams will keep failing because the repos haven't got adapted to the new change in gax. See the follow ups below.

### Fixes in `java-spanner`
image

### Fixes in `java-bigtable`
image

### Follow ups in `java-bigtable`
More failures in java-bigtable to be addressed in that repo:
```
Error:    BigtableTableAdminSettingsTest.testToString:175 expected to contain: totalTimeout=PT13H32M
but was            : BigtableTableAdminSettings{projectId=our-project-85, instanceId=our-instance-06, 
...
```

Fixed in https://github.com/googleapis/java-bigtable/pull/2274

### Follow ups in `java-spanner`
```
Error:  Failures: 
Error:    CompositeTracerTest.testMethodsOverrideMetricsTracer:238 Method not found in compositeTracerMethods: public void com.google.api.gax.tracing.MetricsTracer.attemptFailedDuration(java.lang.Throwable,java.time.Duration)
```
Fixed in https://github.com/googleapis/java-spanner/pull/3200

### CODE REVIEW

**Comment by diegomarquezp** [comment]
More failures in java-bigtable to be addressed in that repo:
```
Error:    BigtableTableAdminSettingsTest.testToString:175 expected to contain: totalTimeout=PT13H32M
but was            : BigtableTableAdminSettings{projectId=our-project-85, instanceId=our-instance-06, 
...
```

Fixed in https://github.com/googleapis/java-bigtable/pull/2274

**Review by JoeWang1127 — APPROVED** [review]

**Review by lqiu96 — APPROVED** [review]

**Comment by diegomarquezp** [comment]
cc: @blakeli0 @lqiu96 

## Moving logic to `ApiTracer` (`BaseApiTracer` is left the same as in `main`)
### java-spanner
image
image


### java-bigtable
image
image
image

**Comment by diegomarquezp** [comment]
> cc: @blakeli0 @lqiu96
> 
> ## Moving logic to `ApiTracer` (`BaseApiTracer` is left the same as in `main`)
> ### java-spanner
> image image
> 
> ### java-bigtable
> image image image

**Comment by diegomarquezp** [comment]
Thanks @blakeli0. The suggestion to remove the overload in `BaseApiTracer` worked.
image
image

**Pull request merged**
