### PR TITLE
chore: add comments to showcase grpc library

### PR DESCRIPTION
**Pull request by diegomarquezp**
This was generated via `mvn install -Pupdate`

### CODE REVIEW

**Comment by blakeli0** [comment]
LGTM. We need to be careful with the timing of merging this PR, if we merge it now and someone regenerates showcase with the existing setup, it would be overridden. Maybe try to include this change in your showcase PR?

**Comment by burkedavison** [comment]
> We need to be careful with the timing of merging this PR, if we merge it now and someone regenerates showcase with the existing setup, it would be overridden.

The required showcase golden tests should fail until then. Please do not merge until ci / showcase (11) and (17) tests are passing.

**Review by meltsufin — COMMENTED** [review]
Is it possible to modify the current showcase generation config to generate with comments?

**Comment by blakeli0** [comment]
> Is it possible to modify the current showcase generation config to generate with comments?

Yeah I believe that's what Diego is working on next.

**Comment by diegomarquezp** [comment]
@blakeli0 @meltsufin I included the [necessary command](https://github.com/googleapis/sdk-platform-java/blob/26b21a405ca7d0e0b56fbae3c103d3f40a82e091/showcase/grpc-gapic-showcase-v1beta1/pom.xml#L68) to include comments with the current showcase configuration.

**Comment by burkedavison** [comment]
@diegomarquezp : The `--experimental...` argument needs to also be added to the `//showcase:verify_grpc` configuration, directly above the `//showcase:update_grpc` profile you've already edited.

**Comment by diegomarquezp** [comment]
thanks @burkedavison. I added the option to such profiles

**Review by blakeli0 — APPROVED** [review]

**Pull request merged**
